## KFold Cross Validation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris=load_iris()

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

##### Logistic Regression

In [4]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [5]:
lr.score(X_test,y_test)

0.9333333333333333

##### SVM

In [6]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

1.0

##### Random Forest

In [7]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9333333333333333

## Cross_val_score function

In [8]:
from sklearn.model_selection import cross_val_score

#### Logistic regression model performance using cross_val_score

In [9]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)

array([0.96, 0.96, 0.94])

#### svm model performance using cross_val_score

In [10]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)

array([0.98, 0.98, 0.96])

#### random forest performance using cross_val_score

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.96])

# Parameter tunning using k fold cross validation

In [12]:
score1=cross_val_score(RandomForestClassifier(n_estimators=5),iris.data,iris.target,cv=10)
np.average(score1)

0.9466666666666667

In [13]:
score2=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=10)
np.average(score2)

0.9533333333333334

In [14]:
score3=cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=10)
np.average(score3)

0.9800000000000001

In [15]:
score4=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=10)
np.average(score4)

0.96

#### Best score is from SVM:0.9800000000000001